### ISSUE TITLE
When using lora to run the rwkv fine-tuning in docker environment, an error is reported, using the enwik8 dataset (about 100m in size), and the following error is reported

### ISSUE THREAD

**Issue by weikeltf** [Blealtan/RWKV-LM-LoRA#12]
RuntimeError: [1] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer.  This may indicate a possible application crash on rank 0 or a network set up issue.

The program startup command:
python3 train.py --load_model /RWKV-4-Raven-7B-v7-ChnEng-20230404-ctx2048.pth --proj_dir /rwkv_f --data_file /enwik8 --data_type utf-8 --vocab_size 50277 --ctx_len 2048 --epoch_steps 600 --epoch_count 30 --epoch_begin 0 --epoch_save 1 --micro_bsz 1 --n_layer 32 --n_embd 4096 --pre_ffn 0 --head_qk 0 --lr_init 2e-5 --lr_final 2e-7 --warmup_steps 0 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 --accelerator gpu --devices 4 --precision fp16 --strategy deepspeed_stage_2 --grad_cp 1 --lora --lora_r 128 --lora_alpha 16 --lora_dropout 0.01 --lora_parts=att,ffn,time,ln

How can i fix it?

**Comment by Blealtan** [comment]
Seems environmental issue unrelated to our project; maybe see [here](https://github.com/pytorch/pytorch/issues/82091).

**Comment by weikeltf** [comment]
Thank for your reply!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Blealtan/RWKV-LM-LoRA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午2:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Blealtan/RWKV-LM-LoRA] When using lora to run the rwkv fine-tuning in docker environment, an error is reported, using the enwik8 dataset (about 100m in size), and the following error is reported (Issue #12)





 
Seems environmental issue unrelated to our project; maybe see here.
