### ISSUE TITLE
shape error in RWKV-4-Raven-3B-v7-ChnEng-20230404-ctx2048.pth

### ISSUE THREAD

**Issue by newcworld** [Blealtan/RWKV-LM-LoRA#13]
```
########## Loading /root/autodl-tmp/text-generation-webui/models/RWKV-4-Raven-3B-v7-ChnEng-20230404-ctx2048.pth... ##########
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/autodl-tmp/RWKV-LM-LoRA/RWKV-v4neo/train.py:351 in <module>                                │
│                                                                                                  │
│   348 │   │   │   if k not in load_keys:                                                         │
│   349 │   │   │   │   load_dict[k] = model.state_dict()[k]                                       │
│   350 │   # If using LoRA, the LoRA keys might be missing in the original model                  │
│ ❱ 351 │   model.load_state_dict(load_dict, strict=(not args.lora))                               │
│   352 │   if os.path.isfile(args.lora_load):                                                     │
│   353 │   │   model.load_state_dict(torch.load(args.lora_load, map_location="cpu"),              │
│   354 │   │   │   │   │   │   │     strict=False)                                                │
│                                                                                                  │
│ /root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py:2041 in load_state_dict  │
│                                                                                                  │
│   2038 │   │   │   │   │   │   ', '.join('"{}"'.format(k) for k in missing_keys)))               │
│   2039 │   │                                                                                     │
│   2040 │   │   if len(error_msgs) > 0:                                                           │
│ ❱ 2041 │   │   │   raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(     │
│   2042 │   │   │   │   │   │   │      self.__class__.__name__, "\n\t".join(error_msgs)))         │
│   2043 │   │   return _IncompatibleKeys(missing_keys, unexpected_keys)                           │
│   2044                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Error(s) in loading state_dict for RWKV:
        size mismatch for emb.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint, the shape in current model is torch.Size([8396, 2560]).
        size mismatch for head.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint, the shape in current model is torch.Size([8396, 2560])
```

**Comment by Blealtan** [comment]
You are using a wrong vocab. Please check your command and data, and see if the `20B_tokenizer` is used to tokenize your input.

**Comment by LiuLinyun** [comment]
I received the same error, I used pretrained model [RWKV-4-Raven-3B-v11-Eng49%25-Chn49%25-Jpn1%25-Other1%25-20230429-ctx4096.pth](https://huggingface.co/BlinkDL/rwkv-4-raven/blob/main/RWKV-4-Raven-3B-v11-Eng49%25-Chn49%25-Jpn1%25-Other1%25-20230429-ctx4096.pth) , but got error:

########## Loading /home/lly/Dev/RWKV-LM-LoRA/pretrained_models/RWKV-4-Raven-3B-v11-Eng49-Chn49-Jpn1-Other1-20230429-ctx4096.pth... ##########
Traceback (most recent call last):
  File "/home/lly/Dev/RWKV-LM-LoRA/RWKV-v4neo/train.py", line 347, in <module>
    model.load_state_dict(load_dict, strict=(not args.lora))
  File "/home/lly/miniconda3/envs/rwkv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for RWKV:
        size mismatch for emb.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint, the shape in current model is torch.Size([13, 2560]).
        size mismatch for head.weight: copying a param with shape torch.Size([50277, 2560]) from checkpoint, the shape in current model is torch. Size([13, 2560]).

And my training command line params are: 

python3 train.py \
  --load_model pretrained_models/RWKV-4-Raven-3B-v11-Eng49-Chn49-Jpn1-Other1-20230429-ctx4096.pth \
  --proj_dir ./finetuned_models \
  --data_file "" \
  --data_type "dummy" \
  --vocab_size 50277 --ctx_len 1024 --epoch_steps 1000 --epoch_count 1000 --epoch_begin 0 --epoch_save 5 --micro_bsz 2 --n_layer 32 --n_embd 2560 --pre_ffn 0 --head_qk 0 --lr_init 1e-4 --lr_final 1e-4 --warmup_steps 0 --beta1 0.9 --beta2 0.999 --adam_eps 1e-8 --accelerator gpu --devices 1 --precision bf16 --strategy deepspeed_stage_2 --grad_cp 0 \
  --lora --lora_r 8 --lora_alpha 16 --lora_dropout 0.01 \
  --lora_parts=att,ffn,time,ln 

In my command line params, I used dummy data, but also got this error.

**Comment by Blealtan** [comment]
@LiuLinyun Sadly I'm not really sure how the dummy data type works, but can you please try with a properly tokenized binidx dataset? Use [this tool](https://github.com/Abel2076/json2binidx_tool) to convert.

**Comment by LiuLinyun** [comment]
@Blealtan I found using dummy data locked vocab size as 13, and I used another binidx dataset solved this problem. Very thank you.

**Comment by gg22mm** [comment]
这个问题我查了一下，好象是内存不够造成的

**Comment by gg22mm** [comment]
这个问题我查了一下，好象是内存不够造成的

**Comment by LiuLinyun** [comment]
@gg22mm 你这个应该是vocab size 设置问题吧（我的也是这个问题），RWKV 的 vocab 大小是 50277，就那个 有 token 索引的 json 文件，里面定义了50277个原子token

**Comment by gg22mm** [comment]
> 50277

不懂了，我用小模型就可以运行起来了。~~
