### ISSUE TITLE
问题已解决：多卡训练时出现core dumped

### ISSUE THREAD

**Issue by magicuter** [Blealtan/RWKV-LM-LoRA#18]
python train.py \
    --load_model "/data/rwkv/models/RWKV-4-Pile-3B-EngChn-test4-20230115.pth" \
    --proj_dir "/data/rwkv/models/lora-3b" \
    --data_file "/home/rwkv/Abel2076/json2binidx_tool/data-simple/rwkv_text_document" \
    --data_type binidx \
    --vocab_size 50277 \
    --ctx_len 256 \
    --accumulate_grad_batches 8 \
    --epoch_steps 10 \
    --epoch_count 10 \
    --epoch_begin 0 \
    --epoch_save 5 \
    --micro_bsz 1 \
    --n_layer 32 \
    --n_embd 2560 \
    --pre_ffn 0 \
    --head_qk 0 \
    --lr_init 1e-5 \
    --lr_final 1e-5 \
    --warmup_steps 0 \
    --beta1 0.9 \
    --beta2 0.999 \
    --adam_eps 1e-8 \
    --accelerator gpu \
    --devices 2 \
    --precision bf16 \
    --strategy deepspeed_stage_2 \
    --grad_cp 1 \
    --lora \
    --lora_r 8 \
    --lora_alpha 32 \
    --lora_dropout 0.01 \
    --lora_parts=att,ffn,time,ln \

环境：rocky 8.6/T4

使用如上的训练命令指定devices为1时可以正常训练，但如果指定devices>1，就会出现core dumped崩溃
oading extension module fused_adam...
Loading extension module fused_adam...
train_cmd.sh: line 34:   894 Bus error               (core dumped) python train.py

@Blealtan

**Comment by Blealtan** [comment]
bus error 看起来很不应该发生，而且软件层面应该也几乎没办法触发，怀疑硬件或驱动问题；我这边多卡是能跑的。

**Comment by magicuter** [comment]
因为使用了docker，需要指定shm-size的大小，不然多卡就会core dumped
