### ISSUE TITLE
v4neo 微调trian.py貌似没有更新 一些参数用不了 例如 'Namespace' object has no attribute 'strategy'

### ISSUE THREAD

**Issue by UnstoppableCurry** [Blealtan/RWKV-LM-LoRA#2]
AttributeError: 'Namespace' object has no attribute 'strategy'
![image](https://user-images.githubusercontent.com/65523997/221411275-294b7680-73f6-4b89-9e50-68eeae860d34.png)

**Comment by Blealtan** [comment]
请检查命令行参数是不是没有传入 `--strategy`。如果还是不行，麻烦发一下完整命令和错误输出，用文本格式这样写
```
    ```
    your command
    ```
```

**Comment by bello7777** [comment]
Hello when I run the train.py 
i got this even after installing DeepSpeed with pip 
########## work in progress ##########
Traceback (most recent call last):
  File "/home/ubuntu/lora/RWKV-v4neo/train.py", line 125, in <module>
    if "deepspeed" in args.strategy:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Blealtan** [comment]
@bello7777 How did you pass `--strategy`? I guess you missed the parameter. It should be like `--strategy deepspeed_stage_2`.

BTW @UnstoppableCurry is it working now?
