### ISSUE TITLE
Low precision LoRA fine tuning

### ISSUE THREAD

**Issue by TehVenomm** [Blealtan/RWKV-LM-LoRA#5]
With the recent advancements in LLaMA lora training, there have been some advancements in regards to training LoRAs at lower precision, allowing for much cheaper hardware requirements on precisions such as 
- 16bit
- 8bit
- 4bit

Example of 4bit PEFT based LoRA fine tuning:

https://github.com/johnsmith0031/alpaca_lora_4bit

Having lowered hardware requirements, even after considering the accuracy drop from lower precision, should allow for more casual interest in the RWKV architecture due to a smaller commitment needed for tuning something.

**Comment by Blealtan** [comment]
Yes, I've been aware of that and I'm waiting for 1. I finish my paper submission (XD), and 2. ChatRWKV determines its way to INT4. Then I'll follow that path and add LoRA on the quantized.

**Comment by Pevernow** [comment]
Are there any new developments regarding Qlora?

**Comment by Pevernow** [comment]
@Blealtan Is this issue still active?

**Comment by Blealtan** [comment]
Sorry but as the HF implementation is getting mature, I would recommend directly using that one. I've seen reports on successfully running QLoRA fine-tuning via HF transformers implementation.

**Comment by john1089** [comment]
@Blealtan could you tell me where the reports are?i can't find any
