### ISSUE TITLE
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

### ISSUE THREAD

**Issue by humanpp** [Blealtan/RWKV-LM-LoRA#54]
Traceback (most recent call last):
  File "/content/train.py", line 116, in <module>
    parser = Trainer.add_argparse_args(parser)
AttributeError: type object 'Trainer' has no attribute 'add_argparse_args'

没这个参数是怎么回事？

**Comment by ByUnal** [comment]
Hello,

Make sure that you've added `--strategy deepspeed_stage_2_offload` while training. If error continues, degrade the pytorch-lightning version. You may wanna try `pip install pytorch-lightning==1.06`.
